"""Add priority and project_type to Project model

Revision ID: 2c5c0a1bc5ca
Revises: 14ed2681b316
Create Date: 2025-06-03 23:51:08.310472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5c0a1bc5ca'
down_revision = '14ed2681b316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('project_type', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('project_type')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
