"""Add azure_oid to User model for SSO

Revision ID: 584f10d288cd
Revises: 1f60986ab669
Create Date: 2025-06-03 05:14:57.601363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584f10d288cd'
down_revision = '1f60986ab669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('azure_oid', sa.String(length=36), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_azure_oid'), ['azure_oid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_azure_oid'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('azure_oid')

    # ### end Alembic commands ###
