"""Add priority and reminder_sent to ProjectTask

Revision ID: 59b48fcf52af
Revises: 2c5c0a1bc5ca
Create Date: 2025-06-03 23:52:27.647001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b48fcf52af'
down_revision = '2c5c0a1bc5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('due_date_reminder_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.drop_column('due_date_reminder_sent')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
