"""Add mime_type and verified to Evidence model

Revision ID: cfcfa3007788
Revises: 59b48fcf52af
Create Date: 2025-06-03 23:53:52.833741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcfa3007788'
down_revision = '59b48fcf52af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_column('verified')
        batch_op.drop_column('mime_type')

    # ### end Alembic commands ###
